### ISSUE TITLE
Duplicate alerts with iam_access_keys_last_used

### ISSUE THREAD

**Issue by johnathanludwig** [EvidentSecurity/custom_signatures#8]
The iam_access_keys_last_used custom signature has the potential to create duplicate alerts for the same resource. 

[Here](https://github.com/EvidentSecurity/custom_signatures/blob/master/iam_access_keys_last_used.rb#L27) the custom signature is looping through the access keys on a user, however the resource specified on alerts is a username. So if a user has multiple access keys, they could have multiple alerts generated.

This could be fixed in a few different ways. We could use the access key as the resource for alerts which would remove the duplicates, but the the pass alerts generated when there are no access keys would still have to be a user. If we went that route it may just be worth removing that alert.

Another way would be to only generate one alert per user and look at all the keys together to determine if it should pass or fail.

**Comment by cityshrimp** [comment]
(This is Ken Chen) I think the former approach is better.  I think this custom signature was made for AWS:IAM-015, which reports on each access key.  It would make this custom signature more consistent with IAM-015.

I can attempt to change the script if we all agree that's the way to go.

**Comment by cityshrimp** [comment]
Discussed with Martinez, and he agrees with using access_key_id as identifier.  I made the changes, and created a pull request here: https://github.com/EvidentSecurity/custom_signatures/pull/9

**Comment by asetiawan** [comment]
Closing old issue. changes was merged
